name: yolov3-tf2-cd
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1
        with:
          python_version: 3.8
          poetry_version: ==1.1.5
          pypi_token: ${{ secrets.PYPI_TOKEN }}
